apiVersion: v1
kind: Pod
metadata:
  namespace: web
  name: nginx-pod
  labels: 
    course: atlas-tech 
spec: 
  containers:
  - name: nginx-container
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi" #megabytes
        cpu: "250m"
    ports: 
    - containerPort: 80