apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-pv
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes: 
    - ReadWriteOnce #specifies the access mode allowing read/write access by a single node, ReadWriteMany - read/write access by multiple nodes
  persistentVolumeReclaimPolicy: Retain #retain volume if pvc is deleted
  storageClassName: manual
  awsElasticBlockStore: 
    volumeID: vol-0707ae92564af8486 #this needs to pre exist in ebs volume
    fsType: xfs