apiVersion: v1
kind: Service
metadata:
  name: nginx-internal-service
  namespace: web
spec:
  type: ClusterIP #type of service (internal communication for pods in a cluster)
  selector: #who is the service routing too
    pod: nginx #should match label of the pods
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80 #port of the pod



