apiVersion: v1
kind: Service 
metadata:
  name: node-port
  namespace: web
spec:
  selector:
    pod: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30030
  type: NodePort