apiVersion: v1
kind: Service
metadata:
  name: prometheus-loadbalancer-service
  namespace: prometheus
spec:
  type: LoadBalancer #type of service (creates an internet facing load balancer)
  selector: #who is the service routing too
    pod: prometheus #should match label of the pods
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9090 #port of the pod