apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - image: httpd:latest
        name: httpd
        ports:
        - containerPort: 3000
        resources:
          requests: #requests how much the pod needs
            cpu: 100m
            memory: 400Mi
          limits: #dont go past this limit or else it will crash 
            cpu: 200m
            memory: 800Mi