apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service
  namespace: web
spec:
  type: NodePort #type of service (nodeport that exposes service on your nodes)
  selector: #who is the service routing too
    pod: nginx #should match label of the pods
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80 #port of the pod
    nodePort: 31030 #range must be between 30000-32767, open port to the node to route to the service