apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer-service
  namespace: web
spec:
  type: LoadBalancer #type of service (creates an internet facing load balancer)
  selector: #who is the service routing too
    pod: nginx #should match label of the pods
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80 #port of the pod