apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: web-pvc
  namespace: webns
spec: 
  storageClassName: manual #match with pv 
  accessModes: #match with pv
    - ReadWriteOnce
  resources: 
    requests: #request how much storage is needed
      storage: 8Gi
  
  