apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sc-pvc
  namespace: webns
spec:
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests:
      storage: 4Gi
  storageClassName: sc-web #match the StorageClass name