apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-web
provisioner: ebs.csi.aws.com #specifies the provisioner which is ebs.csi driver, to create our resource
parameters: 
  type: gp2
  fsType: xfs
volumeBindingMode: WaitForFirstConsumer #specify the volume should be provisioned only when a pod using tnhe pvc is scheduled 
