name: Terraform Destroy
on:
  workflow_dispatch:

jobs:
  infra-deploy:
    runs-on: ubuntu-latest
    steps:
      
      - name: clone-codebase
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3.1.1
        with:
          terraform_version: 1.1.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESSKEY }}
          aws-secret-access-key: ${{ secrets.SECRETACCESSKEY }}
          aws-region: us-east-2

      - name: Terraform init
        id: init
        working-directory: eks-modules
        run: terraform init
      
      - name: update EKS kubeconfig
        run: aws eks update-kubeconfig --name tfcluster --region us-east-2 

      - name: u EKS kubeconfig
        run: |
          kubectl delete --all --all-namespaces
          
      - name: Terraform destroy
        id: destroy
        working-directory: eks-modules
        run: terraform destroy -auto-approve